# Generated by Django 3.0.6 on 2020-05-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
