# Generated by Django 3.0.6 on 2020-05-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_sale_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
