# Generated by Django 3.0.6 on 2020-05-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='sale_commission',
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_commission', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date_applied', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Staff')),
            ],
        ),
    ]
