# Generated by Django 3.0.6 on 2020-05-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20200517_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date_applied',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
