# Generated by Django 3.0.6 on 2020-05-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20200517_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='date',
            new_name='date_sale',
        ),
    ]
