# Generated by Django 3.0.6 on 2020-05-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20200517_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_sale',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
