# Generated by Django 3.0.6 on 2020-08-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20200517_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='staff_id',
            new_name='staff',
        ),
    ]
